{"name": "Попытка входа с невалидными данными: случайные логин и пароль", "status": "passed", "steps": [{"name": "Подготовка тестовых данных для сценария: случайные логин и пароль", "status": "passed", "start": 1758449614070, "stop": 1758449614070}, {"name": "Отправляем POST-запрос для авторизации курьера", "status": "passed", "start": 1758449614070, "stop": 1758449615322}, {"name": "Проверяем код ответа 404", "status": "passed", "start": 1758449615322, "stop": 1758449615322}, {"name": "Проверяем сообщение об ошибке", "status": "passed", "start": 1758449615322, "stop": 1758449615322}], "parameters": [{"name": "test_case", "value": "'случайные логин и пароль'"}, {"name": "credentials", "value": "<function TestCourierLogin.<lambda> at 0x000001F23EA09440>"}, {"name": "expected_status", "value": "404"}, {"name": "expected_message", "value": "'Учетная запись не найдена'"}], "start": 1758449614070, "stop": 1758449615324, "uuid": "dfd72bbb-8ef4-40ae-a6f0-00f608905a5e", "historyId": "08d1b0323b873f13ae684ac3b6fb1e4d", "testCaseId": "505bba1c9113ea857d47e178537c8295", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_negative_cases", "labels": [{"name": "story", "value": "Неуспешная авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "What-Is-Lowe"}, {"name": "thread", "value": "10180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}